Dynamic Experiment
Testing:  1
Traceback (most recent call last):
  File "run_experiments.py", line 175, in <module>
    batch_size=batch_size, plot=False)
  File "run_experiments.py", line 78, in dynamic_experiment
    dyn_exp.run_experiment()
  File "/home/ntumma/code/sketching/experiments.py", line 132, in run_experiment
    sketch_obj = DynamicFDSketch(self.mat, self.l1, self.l2, t, self.batch_size, randomized=self.randomized)
  File "/home/ntumma/code/sketching/fd_sketch.py", line 181, in __init__
    super(DynamicFDSketch, self).__init__(mat, l1, b_size, randomized=randomized, track_del=True)
  File "/home/ntumma/code/sketching/fd_sketch.py", line 64, in __init__
    self._sketch_func = self._svd_sketch
AttributeError: 'DynamicFDSketch' object has no attribute '_svd_sketch'
